#数据库链接配置
jdbc:
  host: 192.168.1.254:3306 #数据库ip、端口
  database: inxedu_customer_chiyewangluoyuanma_wx #数据库库名
  #数据库账号密码
  username: admin268xue
  password: admin268xue

#redis 缓存
redis:
  host: 192.168.1.254
  port: 6379
  pass: rgPt1hBdqPtYJ0acpnfdmWbSHt09kH5T

#upload image path图片上传路径，统一部署时，目录设置为inxedu_web下
file:
  root: E:\项目\驰业网络\inxedu_web\inxedu_web\src\main\webapp

#Cookie域
mydomain:

#项目域名
contextPath: http://127.0.0.1

#项目名（上传类型为空时统一上传到此目录下）
projectName: inxedu

#允许上传类型
imageType: jpg,png,jpeg,odt
